name: Tests & Coverage
on:
  pull_request:
jobs:
  build:
    defaults:
      run:
        working-directory: ./app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run test:cov

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: /app/coverage/coverage-final.json
