name: Tests & Coverage
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write
  checks: write
  issues: write
  statuses: write

jobs:
  build:
    defaults:
      run:
        working-directory: ./app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run test:cov

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./app/coverage/coverage-summary.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
